version: '3.8'

services:
    server:
        restart: unless-stopped
        ports:
            - 8000:8000
        build:
            context: .
            dockerfile: ./docker/configuration/Dockerfile
        entrypoint: /bom-server/docker/configuration/server-entrypoint.sh
        volumes:
            - static_volume:/bom-server/staticfiles
        expose:
            - 8000     
        environment:
            DEBUG: "False"
            # ALLOWED_HOSTS: "localhost,192.168.109.123,http://192.168.109.123:8080"
            # CORS_ALLOWED_ORIGINS : "http://192.168.109.123:8080"
            CELERY_BROKER_URL: "redis://redis:6379/0"
            CELERY_RESULT_BACKEND: "redis://redis:6379/0"
        depends_on: 
            - db
        # scale: 4  # Adjust the number of replicas as needed
    nginx:
        # restart: always
        # image: nginx:1.23-alpine
        build: ./docker/nginx
        ports:
            - 8080:80
        depends_on:
            - server
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - static_volume:/bom-server/staticfiles
    redis:
        restart: unless-stopped
        image: redis:7.0.5-alpine
        expose:
            - 6379
    db:
      image: postgres:14.1-alpine
      restart: unless-stopped
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=bom
      ports:
        - 5432:5432
      expose:
            - 5432
      volumes: 
        - postgres_data:/var/lib/postgresql/data
volumes:
    postgres_data: 
    static_volume: 
