version: '2'

services:
    nginx:
        restart: always
        image: nginx:1.23-alpine
        ports:
            - 8080:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./static:/bom-server/static
    server:
        restart: unless-stopped
        ports:
            - 8000:8000
        build:
            context: .
            dockerfile: ./docker/configuration/Dockerfile
        entrypoint: /bom-server/docker/configuration/server-entrypoint.sh
        volumes:
            - ./static:/bom-server/static
        expose:
            - 8000     
        environment:
            DEBUG: "True"
            CELERY_BROKER_URL: "redis://redis:6379/0"
            CELERY_RESULT_BACKEND: "redis://redis:6379/0"
    redis:
        restart: unless-stopped
        image: redis:7.0.5-alpine 
        expose:
            - 6379
    db:
      image: postgres:14.1-alpine
      restart: unless-stopped
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=bom
      ports:
        - 5432:5432
      expose:
            - 5432
      volumes: 
        - postgres_data:/var/lib/postgresql/data
volumes:
    postgres_data: {}
    static_volume: {}
