# Generated by Django 4.2.3 on 2023-09-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("component", "0002_providedocumentcode_bomdocumentcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="bomdocumentcode",
            name="hyper_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="providedocumentcode",
            name="hyper_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
